#!/bin/bash
# 📋 AWS SageMaker Cost Management - Quick Reference
# All available commands for scanning and managing SageMaker costs

echo "🚨 AWS SageMaker Cost Management Tools"
echo "======================================"
echo ""

echo "📋 Available Scripts:"
echo "--------------------"
echo "1. 🔍 cost_estimator_remove_resource.py - Main Python scanner (full features)"
echo "2. 🚀 scan_sagemaker_costs.sh - Shell wrapper (easy to use)"
echo "3. 🎭 demo_cost_scanner.py - Demo with sample data"
echo "4. 📚 README.md - Complete documentation"
echo ""

echo "🚀 Quick Commands:"
echo "----------------"
echo "# Emergency scan (no credentials needed - demo data)"
echo "./demo_cost_scanner.py"
echo ""

echo "# Real AWS scan (requires AWS credentials)"
echo "./scan_sagemaker_costs.sh scan"
echo "./scan_sagemaker_costs.sh cleanup"
echo "./scan_sagemaker_costs.sh scan us-west-2"
echo ""

echo "# Python script directly"
echo "python3 cost_estimator_remove_resource.py --scan"
echo "python3 cost_estimator_remove_resource.py --cleanup"
echo "python3 cost_estimator_remove_resource.py --region us-east-1"
echo ""

echo "⚠️  AWS Credentials Setup:"
echo "-------------------------"
echo "Before running real scans, configure AWS:"
echo ""
echo "Option 1 - AWS CLI:"
echo "  aws configure"
echo ""
echo "Option 2 - Environment Variables:"
echo "  export AWS_ACCESS_KEY_ID='your-key'"
echo "  export AWS_SECRET_ACCESS_KEY='your-secret'"
echo "  export AWS_DEFAULT_REGION='us-east-1'"
echo ""

echo "📊 What Gets Scanned:"
echo "-------------------"
echo "✅ SageMaker Endpoints (~$1-4/hour each)"
echo "✅ Training Jobs (~$1-4/hour each)" 
echo "✅ Notebook Instances (~$0.05-1/hour each)"
echo "✅ S3 Storage (~$0.01-1/day)"
echo ""

echo "🧹 What Gets Cleaned:"
echo "--------------------"
echo "🗑️  Deletes InService endpoints"
echo "⏹️  Stops running training jobs"
echo "🛑 Stops notebook instances"
echo "💰 Calculates cost savings"
echo ""

echo "🎯 File Locations:"
echo "-----------------"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
echo "📁 Scripts: $SCRIPT_DIR"
echo "📖 README: $SCRIPT_DIR/README.md"
echo "🔧 Main tool: $SCRIPT_DIR/cost_estimator_remove_resource.py"
echo ""

echo "🆘 Emergency Stop Charges:"
echo "-------------------------" 
echo "Run this immediately if you see unexpected charges:"
echo "  ./scan_sagemaker_costs.sh cleanup"
echo ""
echo "Or from Python directly:"
echo "  python3 cost_estimator_remove_resource.py --cleanup"
echo ""

echo "💡 Pro Tips:"
echo "-----------"
echo "• Set up AWS billing alerts to prevent surprises"
echo "• Run regular scans to catch accidental resources"
echo "• Use specific regions: --region us-west-2"
echo "• Check multiple regions if unsure"
echo "• Verify before cleanup - deleted resources are expensive to recreate"
echo ""

echo "📞 Support:"
echo "----------"
echo "• Documentation: cat README.md"
echo "• Demo output: ./demo_cost_scanner.py"
echo "• Help: python3 cost_estimator_remove_resource.py --help"